name: Test SparseVector

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Google Test
        run: |
          sudo apt update
          sudo apt install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp libgtest*.a /usr/lib

      - name: Build and run tests
        run: |
          make
          make run

      - name: Cleanup
        run: make clean
